sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t umeshsb/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true umeshsb/react-test npm test -- --coverage

after-success:
    - docker build -t umeshbiradar/multi-client ./client
    - docker build -t umeshbiradar/multi-nginx ./nginx
    - docker build -t umeshbiradar/multi-server ./server
    - docker build -t umeshbiradar/multi-worker ./worker
    # Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    # Take these images and push them to docker hub
    - docker push umeshbiradar/multi-client
    - docker push umeshbiradar/multi-nginx
    - docker push umeshbiradar/multi-server
    - docker push umeshbiradar/multi-worker


